<?php
$products = $this->getRecentProducts(); // Productos recientes

foreach($products as $product):?>

<div style="text-align: center; width: 300px; margin-bottom: 50px;">
	<p>
		<a href="<?php echo $product->link_product;?>">
			<img src="<?php echo $product->image;?>" />
			<?php echo $product->name; ?>
		</a>
	</p>
	<p><?php echo $product->price;?></p>
	<p>
		<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
				onclick="setLocation('<?php echo $product->add_cart_url; ?>')">
			<span><span><?php echo $this->__('Add to Cart') ?></span></span>
		</button>
	</p>
</div>

<?php endforeach;?>

